ALTER TABLE orders
ADD COLUMN IF NOT EXISTS product_id BIGINT,
ADD COLUMN IF NOT EXISTS product_slug VARCHAR(255),
ADD COLUMN IF NOT EXISTS product_name VARCHAR(255),
ADD COLUMN IF NOT EXISTS product_image_url TEXT;